# This rule is not used by the project ingress-auditor itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over ingress-audit.morty.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ingress-auditor
    app.kubernetes.io/managed-by: kustomize
  name: ingresstlslog-admin-role
rules:
- apiGroups:
  - ingress-audit.morty.dev
  resources:
  - ingresstlslogs
  verbs:
  - '*'
- apiGroups:
  - ingress-audit.morty.dev
  resources:
  - ingresstlslogs/status
  verbs:
  - get
