# This rule is not used by the project ingress-auditor itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to ingress-audit.morty.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ingress-auditor
    app.kubernetes.io/managed-by: kustomize
  name: ingresstlslog-viewer-role
rules:
- apiGroups:
  - ingress-audit.morty.dev
  resources:
  - ingresstlslogs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ingress-audit.morty.dev
  resources:
  - ingresstlslogs/status
  verbs:
  - get
