apiVersion: ingress-audit.morty.dev/v1alpha1
kind: IngressTLSLog
metadata:
  labels:
    app.kubernetes.io/name: ingress-auditor
    app.kubernetes.io/managed-by: kustomize
  name: ingresstlslog-sample
spec:
  generationTimestamp: "2025-12-12T00:00:00Z"
  ingressName: ingress-example
  level: Error
  message: the secretName does not define in ingress
  namespace: ns-example
