# TLS with secret but secret crt with wrong host
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-2
  namespace: ns-2
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - https-example-2.foo.com
    secretName: secret-tls
  rules:
  - host: https-example-2.foo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-2
            port:
              number: 80
