name: E2E Tests

on:
  push:
  pull_request:

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install the latest version of Minikube
        run: |
          curl -LO https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64

      - name: Verify Minikube installation
        run: minikube version

      - name: Install the latest version of get_helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4
          chmod +x get_helm.sh
          ./get_helm.sh

      - name: Verify helm installation
        run: helm version

      # - name: Install internal CA
      #   run: |
      #     echo "${{ secrets.INTERNAL_CA_CERT_5 }}" > internal-ca.crt
      #     sudo cp internal-ca.crt /usr/local/share/ca-certificates/internal-ca.crt
      #     sudo update-ca-certificates
      
      # - name: Verify CA is trusted
      #   run: |
      #     openssl verify -CApath /etc/ssl/certs internal-ca.crt

      - name: Running Test e2e
        run: |
          go mod tidy
          make test-e2e

      # uncomment for debugging
      # - name: TLS debug
      #   if: failure()
      #   run: |
      #     echo "=== TLS handshake ==="
      #     openssl s_client \
      #       -connect https-example-5.foo.com:443 \
      #       -servername https-example-5.foo.com \
      #       -showcerts </dev/null

      #     echo "=== Verify ==="
      #     openssl s_client \
      #     -connect https-example-5.foo.com:443 \
      #     -servername https-example-5.foo.com \
      #     -CAfile internal-ca.crt \
      #     -verify_return_error \
      #     -showcerts </dev/null